### ISSUE TITLE
add support for plain bundle format

### ISSUE THREAD

**Issue by tylerslaton** [operator-framework/combo#84]
Since RukPak is starting to come to its own, it makes sense for Combo to be a first example bundle for its plain manifests bundle format. Proof of concept for this has already been done via the `quay.io/tyslaton/combo-plain-bundle:v0.0.1` image.

It was constructed using the following Dockerfile:

```dockerfile
FROM scratch
LABEL manifests="/manifests"
COPY ./manifests /manifests
```

Which loads in the manifests from `combos` manifest directory. As a result, we would like an official support for this so that RukPak can use it in its internal documentation as an example for users to get started with.

# Acceptance Criteria
- [x] Release schedule determined
- [x] Dockerfile.plainbundle
- [x] Make target
- [x] Necassary CI actions

**Comment by exdx** [comment]
There is a gap in documentation in what a plain/k8s bundle looks like right now, and having combo as an example is very helpful in the effort to document this new format. I do think we need to settle on a spec, for example the manifests location and the label name,  as a prereq for really publishing this new format. combo should be an example of the spec, and since it's the very first officially supported plain bundle, it's important to have it match exactly what we intend with the new bundle format.

**Comment by exdx** [comment]
Update: the plain bundle spec landed in https://github.com/operator-framework/rukpak/pull/149 and the combo manifests directory was updated to conform to the spec in #92. At this point combo is equipped as a plain bundle, but further actions defined in the A/C are still todos.

**Comment by oceanc80** [comment]
For now, releases will be triggered manually via versioned releases and every merge to main. This issue tracks the need for a regular release cadence going forward as Combo matures: https://github.com/operator-framework/combo/issues/100
